FROM node:20-alpine as build
WORKDIR /app
COPY . .
RUN npm install && npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY package.json .
RUN npm install --omit=dev
USER node
EXPOSE 3000
CMD ["node", "dist/main"]