FROM node:20-alpine as build
WORKDIR /app
COPY . .
RUN npm install

FROM node:20-alpine
WORKDIR /app
COPY --from=build /app ./
COPY package.json .
RUN npm install --omit=dev
USER node
EXPOSE 3001
CMD ["node", "dist/main"]