server {
  listen 80;

  location / {
    proxy_pass http://spa:80;
  }

  location /ssr/ {
    proxy_pass http://ssr:4000/;
  }

  location /api/ {
    proxy_pass http://api:3000/;
  }

  location /express/ {
    proxy_pass http://express:3000/;
  }

  location /oracle/ {
    proxy_pass http://oracle-api:5000/;
  }
}
