server {
    listen 80 http2;
    listen 443 ssl http2;

    server_name _;

    gzip on;
    gzip_types text/plain application/json text/css application/javascript;

    location /angular-spa/ {
        proxy_pass http://spa:81;
    }

    location /angular-ssr/ {
        proxy_pass http://ssr:4000;
    }

    location /nestjs/ {
        proxy_pass http://nestjs-api:3000;
    }

    location /express/ {
        proxy_pass http://express-app:3001;
    }

    location /oracle/ {
        proxy_pass http://oracle-node-api:8888;
    }

    modsecurity on;
    modsecurity_rules_file /etc/nginx/modsec/modsecurity.conf;
}
