# Stage 1: Build the Angular app
FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build --prod

# Stage 2: Serve with Nginx
FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY ngnix/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist/spa /usr/share/nginx/html

RUN addgroup -g 1001 appgroup && adduser -D -G appgroup -u 1001 appuser
USER appuser

EXPOSE 81
CMD ["nginx", "-g", "daemon off;"]